### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by oubaydos** [savajapurva/E-Learning-MERN#1]
hey, 
the fisrt time i cloned this repo and tried to start it (npm run dev), it's giving me : 
**TypeError: Cannot read property 'apply' of undefined**
```  621 | 

  622 |   return funcs.reduce(function (a, b) {

  623 |     return function () {

>> 624 |       return a(b.apply(void 0, arguments));

  625 |     };

  626 |   });

  627 | }```

**Comment by danielMugisha** [comment]
same here

**Comment by danielMugisha** [comment]
found out it might be related to mongodb connection

**Comment by oubaydos** [comment]
@danielMugisha  let me know if u fixed it, seems like if the owner is long gone

**Comment by danielMugisha** [comment]
actually it was not mongodb connection, it is an issue with redux check 
https://stackoverflow.com/questions/53514758/redux-typeerror-cannot-read-property-apply-of-undefined
install redux devtools chrome extension and node package (npm i redux-devtools --save)

**Comment by oubaydos** [comment]
it worked, thanks man
